//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace P4_WebBrowserApp.cn.com.webxml.fy {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EnglishChineseSoap", Namespace="http://WebXml.com.cn/")]
    public partial class EnglishChinese : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TranslatorOperationCompleted;
        
        private System.Threading.SendOrPostCallback TranslatorStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback TranslatorReferStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback TranslatorSentenceStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuggestWordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMp3OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EnglishChinese() {
            this.Url = global::P4_WebBrowserApp.Properties.Settings.Default.P4_WebBrowserApp_cn_com_webxml_fy_EnglishChinese;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TranslatorCompletedEventHandler TranslatorCompleted;
        
        /// <remarks/>
        public event TranslatorStringCompletedEventHandler TranslatorStringCompleted;
        
        /// <remarks/>
        public event TranslatorReferStringCompletedEventHandler TranslatorReferStringCompleted;
        
        /// <remarks/>
        public event TranslatorSentenceStringCompletedEventHandler TranslatorSentenceStringCompleted;
        
        /// <remarks/>
        public event SuggestWordCompletedEventHandler SuggestWordCompleted;
        
        /// <remarks/>
        public event GetMp3CompletedEventHandler GetMp3Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/Translator", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Translator(string wordKey) {
            object[] results = this.Invoke("Translator", new object[] {
                        wordKey});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TranslatorAsync(string wordKey) {
            this.TranslatorAsync(wordKey, null);
        }
        
        /// <remarks/>
        public void TranslatorAsync(string wordKey, object userState) {
            if ((this.TranslatorOperationCompleted == null)) {
                this.TranslatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslatorOperationCompleted);
            }
            this.InvokeAsync("Translator", new object[] {
                        wordKey}, this.TranslatorOperationCompleted, userState);
        }
        
        private void OnTranslatorOperationCompleted(object arg) {
            if ((this.TranslatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslatorCompleted(this, new TranslatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/TranslatorString", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] TranslatorString(string wordKey) {
            object[] results = this.Invoke("TranslatorString", new object[] {
                        wordKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void TranslatorStringAsync(string wordKey) {
            this.TranslatorStringAsync(wordKey, null);
        }
        
        /// <remarks/>
        public void TranslatorStringAsync(string wordKey, object userState) {
            if ((this.TranslatorStringOperationCompleted == null)) {
                this.TranslatorStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslatorStringOperationCompleted);
            }
            this.InvokeAsync("TranslatorString", new object[] {
                        wordKey}, this.TranslatorStringOperationCompleted, userState);
        }
        
        private void OnTranslatorStringOperationCompleted(object arg) {
            if ((this.TranslatorStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslatorStringCompleted(this, new TranslatorStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/TranslatorReferString", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] TranslatorReferString(string wordKey) {
            object[] results = this.Invoke("TranslatorReferString", new object[] {
                        wordKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void TranslatorReferStringAsync(string wordKey) {
            this.TranslatorReferStringAsync(wordKey, null);
        }
        
        /// <remarks/>
        public void TranslatorReferStringAsync(string wordKey, object userState) {
            if ((this.TranslatorReferStringOperationCompleted == null)) {
                this.TranslatorReferStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslatorReferStringOperationCompleted);
            }
            this.InvokeAsync("TranslatorReferString", new object[] {
                        wordKey}, this.TranslatorReferStringOperationCompleted, userState);
        }
        
        private void OnTranslatorReferStringOperationCompleted(object arg) {
            if ((this.TranslatorReferStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslatorReferStringCompleted(this, new TranslatorReferStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/TranslatorSentenceString", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] TranslatorSentenceString(string wordKey) {
            object[] results = this.Invoke("TranslatorSentenceString", new object[] {
                        wordKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void TranslatorSentenceStringAsync(string wordKey) {
            this.TranslatorSentenceStringAsync(wordKey, null);
        }
        
        /// <remarks/>
        public void TranslatorSentenceStringAsync(string wordKey, object userState) {
            if ((this.TranslatorSentenceStringOperationCompleted == null)) {
                this.TranslatorSentenceStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslatorSentenceStringOperationCompleted);
            }
            this.InvokeAsync("TranslatorSentenceString", new object[] {
                        wordKey}, this.TranslatorSentenceStringOperationCompleted, userState);
        }
        
        private void OnTranslatorSentenceStringOperationCompleted(object arg) {
            if ((this.TranslatorSentenceStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslatorSentenceStringCompleted(this, new TranslatorSentenceStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/SuggestWord", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SuggestWord(string wordKey) {
            object[] results = this.Invoke("SuggestWord", new object[] {
                        wordKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SuggestWordAsync(string wordKey) {
            this.SuggestWordAsync(wordKey, null);
        }
        
        /// <remarks/>
        public void SuggestWordAsync(string wordKey, object userState) {
            if ((this.SuggestWordOperationCompleted == null)) {
                this.SuggestWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuggestWordOperationCompleted);
            }
            this.InvokeAsync("SuggestWord", new object[] {
                        wordKey}, this.SuggestWordOperationCompleted, userState);
        }
        
        private void OnSuggestWordOperationCompleted(object arg) {
            if ((this.SuggestWordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuggestWordCompleted(this, new SuggestWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/GetMp3", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetMp3(string Mp3) {
            object[] results = this.Invoke("GetMp3", new object[] {
                        Mp3});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMp3Async(string Mp3) {
            this.GetMp3Async(Mp3, null);
        }
        
        /// <remarks/>
        public void GetMp3Async(string Mp3, object userState) {
            if ((this.GetMp3OperationCompleted == null)) {
                this.GetMp3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMp3OperationCompleted);
            }
            this.InvokeAsync("GetMp3", new object[] {
                        Mp3}, this.GetMp3OperationCompleted, userState);
        }
        
        private void OnGetMp3OperationCompleted(object arg) {
            if ((this.GetMp3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMp3Completed(this, new GetMp3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void TranslatorCompletedEventHandler(object sender, TranslatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranslatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void TranslatorStringCompletedEventHandler(object sender, TranslatorStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranslatorStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslatorStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void TranslatorReferStringCompletedEventHandler(object sender, TranslatorReferStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranslatorReferStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslatorReferStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void TranslatorSentenceStringCompletedEventHandler(object sender, TranslatorSentenceStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranslatorSentenceStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslatorSentenceStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SuggestWordCompletedEventHandler(object sender, SuggestWordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuggestWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuggestWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetMp3CompletedEventHandler(object sender, GetMp3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMp3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMp3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591