//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P4_WebBrowserApp.TranslationServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="TranslationServiceReference.EnglishChineseSoap")]
    public interface EnglishChineseSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/Translator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Translator(string wordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/Translator", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TranslatorAsync(string wordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/TranslatorString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] TranslatorString(string wordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/TranslatorString", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> TranslatorStringAsync(string wordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/TranslatorReferString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] TranslatorReferString(string wordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/TranslatorReferString", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> TranslatorReferStringAsync(string wordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/TranslatorSentenceString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] TranslatorSentenceString(string wordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/TranslatorSentenceString", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> TranslatorSentenceStringAsync(string wordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/SuggestWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SuggestWord(string wordKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/SuggestWord", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> SuggestWordAsync(string wordKey);
        
        // CODEGEN: 参数“GetMp3Result”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/GetMp3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        P4_WebBrowserApp.TranslationServiceReference.GetMp3Response GetMp3(P4_WebBrowserApp.TranslationServiceReference.GetMp3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/GetMp3", ReplyAction="*")]
        System.Threading.Tasks.Task<P4_WebBrowserApp.TranslationServiceReference.GetMp3Response> GetMp3Async(P4_WebBrowserApp.TranslationServiceReference.GetMp3Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMp3", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class GetMp3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public string Mp3;
        
        public GetMp3Request() {
        }
        
        public GetMp3Request(string Mp3) {
            this.Mp3 = Mp3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMp3Response", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class GetMp3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetMp3Result;
        
        public GetMp3Response() {
        }
        
        public GetMp3Response(byte[] GetMp3Result) {
            this.GetMp3Result = GetMp3Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EnglishChineseSoapChannel : P4_WebBrowserApp.TranslationServiceReference.EnglishChineseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnglishChineseSoapClient : System.ServiceModel.ClientBase<P4_WebBrowserApp.TranslationServiceReference.EnglishChineseSoap>, P4_WebBrowserApp.TranslationServiceReference.EnglishChineseSoap {
        
        public EnglishChineseSoapClient() {
        }
        
        public EnglishChineseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnglishChineseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnglishChineseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnglishChineseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Translator(string wordKey) {
            return base.Channel.Translator(wordKey);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TranslatorAsync(string wordKey) {
            return base.Channel.TranslatorAsync(wordKey);
        }
        
        public string[] TranslatorString(string wordKey) {
            return base.Channel.TranslatorString(wordKey);
        }
        
        public System.Threading.Tasks.Task<string[]> TranslatorStringAsync(string wordKey) {
            return base.Channel.TranslatorStringAsync(wordKey);
        }
        
        public string[] TranslatorReferString(string wordKey) {
            return base.Channel.TranslatorReferString(wordKey);
        }
        
        public System.Threading.Tasks.Task<string[]> TranslatorReferStringAsync(string wordKey) {
            return base.Channel.TranslatorReferStringAsync(wordKey);
        }
        
        public string[] TranslatorSentenceString(string wordKey) {
            return base.Channel.TranslatorSentenceString(wordKey);
        }
        
        public System.Threading.Tasks.Task<string[]> TranslatorSentenceStringAsync(string wordKey) {
            return base.Channel.TranslatorSentenceStringAsync(wordKey);
        }
        
        public string[] SuggestWord(string wordKey) {
            return base.Channel.SuggestWord(wordKey);
        }
        
        public System.Threading.Tasks.Task<string[]> SuggestWordAsync(string wordKey) {
            return base.Channel.SuggestWordAsync(wordKey);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        P4_WebBrowserApp.TranslationServiceReference.GetMp3Response P4_WebBrowserApp.TranslationServiceReference.EnglishChineseSoap.GetMp3(P4_WebBrowserApp.TranslationServiceReference.GetMp3Request request) {
            return base.Channel.GetMp3(request);
        }
        
        public byte[] GetMp3(string Mp3) {
            P4_WebBrowserApp.TranslationServiceReference.GetMp3Request inValue = new P4_WebBrowserApp.TranslationServiceReference.GetMp3Request();
            inValue.Mp3 = Mp3;
            P4_WebBrowserApp.TranslationServiceReference.GetMp3Response retVal = ((P4_WebBrowserApp.TranslationServiceReference.EnglishChineseSoap)(this)).GetMp3(inValue);
            return retVal.GetMp3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P4_WebBrowserApp.TranslationServiceReference.GetMp3Response> P4_WebBrowserApp.TranslationServiceReference.EnglishChineseSoap.GetMp3Async(P4_WebBrowserApp.TranslationServiceReference.GetMp3Request request) {
            return base.Channel.GetMp3Async(request);
        }
        
        public System.Threading.Tasks.Task<P4_WebBrowserApp.TranslationServiceReference.GetMp3Response> GetMp3Async(string Mp3) {
            P4_WebBrowserApp.TranslationServiceReference.GetMp3Request inValue = new P4_WebBrowserApp.TranslationServiceReference.GetMp3Request();
            inValue.Mp3 = Mp3;
            return ((P4_WebBrowserApp.TranslationServiceReference.EnglishChineseSoap)(this)).GetMp3Async(inValue);
        }
    }
}
